In [1]:
import pandas as pd
import numpy as np
import pickle
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head(3)

area   price
0  2600  550000
1  3000  565000
2  3200  610000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [22]:
model.predict([[5000]])

array([859554.79452055])

# Pickle libarary

In [15]:
import pickle
with open('model_pickle', 'wb') as file:
    pickle.dump(model,file)

In [17]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [19]:
mp.coef_

array([135.78767123])

In [20]:
mp.intercept_

180616.43835616432

In [21]:
mp.predict([[5000]])

array([859554.79452055])

# Joblib Libarary

In [24]:
from sklearn.externals import joblib
joblib.dump(model, 'model_joblib')

C:\Users\ImdaduL Haque\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['model_joblib']

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.coef_

array([135.78767123])

In [28]:
mj.intercept_

180616.43835616432

In [29]:
mj.predict([[5000]])

array([859554.79452055])