In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df= pd.read_csv("HomePricesMoroeTownship.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
import math
md = df.bedrooms.median()
md

4.0

In [13]:
df.bedrooms = df.bedrooms.fillna(md)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
model = linear_model.LinearRegression()
model.fit(df.drop('price', axis='columns'), df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
model.predict([[3000, 3, 40]])

array([498408.25158031])

In [19]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [20]:
model.intercept_

221323.00186540408

In [30]:
112.06244194*3000 + 23388.88007794*3 -3231.71790863*40 +221323.00186540408

498408.2515740241

In [24]:
model.predict([[2500, 4, 5]])

array([578876.03748933])

In [25]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [28]:
model.intercept_

221323.00186540408

In [29]:
112.06244194*2500 + 23388.88007794*4 -3231.71790863*5 + 221323.00186540408

578876.0374840142