In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df = pd.read_csv("hiring.csv")
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [16]:
import math
md = df.test_score.median()
md

8.0

In [19]:
df.experience.median()

6.0

In [21]:
df.test_score = df.test_score.fillna(md)
df

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [22]:
model = linear_model.LinearRegression()
model.fit(df.drop('salary', axis='columns'), df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
model.predict([[2,9,6]])

array([47056.91056911])

In [25]:
model.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [26]:
model.intercept_

11869.91869918695

In [27]:
2813.00813008*2 + 1333.33333333*9 + 2926.82926829*6 + 11869.91869918695

47056.910569056956

In [28]:
model.predict([[12, 10, 10]])

array([88227.64227642])

In [29]:
model.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [30]:
model.intercept_

11869.91869918695

In [31]:
2813.00813008*12 + 1333.33333333*10 + 2926.82926829*10 + 11869.91869918695

88227.64227634695